[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
local = "127.0.0.1:8545"
# sepolia = "https://rpc.particle.network/evm-chain?chainId=11155111&projectUuid=41775b33-7239-428c-8eea-73da3c366283&projectKey=cHcl44YvbInjYUts5LkadhTjJBfzgfPCc2vLd957"
sepolia = "https://1rpc.io/sepolia"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
